# Generated by Django 4.0.6 on 2022-11-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_nombre', models.CharField(max_length=100, verbose_name='apellido_nombre')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
                'ordering': ['apellido_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre')),
                ('especie', models.CharField(max_length=30, verbose_name='especie')),
                ('raza', models.CharField(max_length=30, verbose_name='raza')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha_nacimiento')),
                ('foto', models.ImageField(upload_to='pacientes')),
                ('peso', models.FloatField(verbose_name='peso')),
                ('fecha_visita', models.DateField(auto_now_add=True, verbose_name='fecha_visita')),
                ('comentarios', models.TextField(max_length=255)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.familia')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
